name: Build .NET Project

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore SaharBeautySalonBack.sln

    - name: Build
      run: dotnet build SaharBeautySalonBack.sln --configuration Release --no-restore

    - name: Publish API
      run: dotnet publish src/03.RestApi/BeautySalon.RestApi/BeautySalon.RestApi.csproj --configuration Release --no-build -o publish
    
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t beauty-api:latest . 